### PR TITLE
Add greek translation.

### PR DESCRIPTION
**Pull request by xarhsdev**
Add el.js translation file. Work in progress.

### CODE REVIEW

**Comment by timothyylim** [comment]
Great work @xarhsdev , if you are happy with it I'll merge it in right now. Otherwise, you can keep making changes until you are :)

**Comment by xarhsdev** [comment]
hi @timothyylim, please do not merge it until it is complete! Just check if the master branch it's ok for this pull request. I will let you know, when the job is done.

------ Original Message ------

**Comment by xarhsdev** [comment]
@timothyylim finished. Free to merge!

**Comment by timothyylim** [comment]
Well done @xarhsdev! :1st_place_medal:

**Pull request merged**
