### PR TITLE
lossless image compression, 34kb saved, up to 90% per file

### PR DESCRIPTION
**Pull request by drsassafras**

### CODE REVIEW

**Comment by drsassafras** [comment]
The UTF-BOM encoding can be really nasty as it can cause strange errors when its not handled properly. Ive converted these files to UTF, otherwise there content has not changed.

**Comment by falcon-git** [comment]
Looks scary and we don't change ckeditor like this. We fetch updates from the official version.

**Comment by drsassafras** [comment]
Each file can be confirmed to be identical. What about this looks scary?

Would submitting a patch (or pull request) to the official version be more fruitful?

**Comment by icc** [comment]
Hi,

Yes, all the [CKEditor](https://github.com/ckeditor) files are copied over into this repo, so any changes made here will just be overwritten on the next update.

**Pull request closed without merging**
