### PR TITLE
add functionality for custom HTML5 video quality labels

### PR DESCRIPTION
**Pull request by otacke**
implements [custom video quality labels as requested and discussed in the forum](https://h5p.org/node/44733)

requires [pull request for h5p-interactive-video](https://github.com/h5p/h5p-interactive-video/pull/47) and [pull request for h5p-video](https://github.com/h5p/h5p-video/pull/12)

### CODE REVIEW

**Comment by timothyylim** [comment]
Good stuff, @otacke. 
I've made an issue [here for review](https://h5ptechnology.atlassian.net/browse/HFP-730)

**Comment by otacke** [comment]
Great! And I am going to beautify the code some more.

**Comment by otacke** [comment]
Just came across [Jira issue HFP-260](https://h5ptechnology.atlassian.net/browse/HFP-260). Looks great, but it'll mean to rewrite some of this pull request's code.

**Comment by otacke** [comment]
Thanks for your review!

I hope to come around to implement the changes soon.

## tech
1. I'm not sure whether I caused that. Skipping ...
2. I guess I didn't do that, because I think there already was a bug report on the forum addressing that. Skipping ...
3. [I had some help with the hidden semantic property :-)](https://h5p.org/comment/9851#comment-9851). Skipping ...

## UX, etc.
1. I'd love to put it somewhere else, but I'm not sure where a better place might be without being able to react to the variable number of videos and their types in semantics.
2. I don't think I encountered the dialog closing issue before, but you're right about the YT issue.
3. Oh oh. That's not a good sign. I wonder if I messed up my repo and this is not the final version.
4. Thanks for checking! I should definitely validate/sanitize the input beforehand.
5. Agreed, but I didn't create it, I just extended it ;-)

**Pull request closed without merging**
