### PR TITLE
This change adds SVG as a valid mime

### PR DESCRIPTION
**Pull request by cperg**
The tests for height and width are pulled differently than a bit mapped image.

### CODE REVIEW

**Comment by pjotrsavitski** [comment]
Looks like this has been here for too long and has issues with the current codebase.

Has it been disregarded for a specific reason or something else?

The changes required seem to be the:
* allow new file mime and extension on the backend
* allow specific mime on the JS side as the acceptable mimes

There might also be an issue with determining width and height of the uploaded file. Image files seem to also have previews and resize possibility, that one will not play well with SVG. There might be something else.

Is there any interest for this at all?

**Comment by falcon-git** [comment]
I think the issue has been forgotten somehow. Perhaps one of my e-mail filters swallowed it :/ Are you interested in pursuing this one? I'm not sure if svg should be an image or a new type (Vector graphic for instance). If it is an image it must be possible to threat it as one. Perhaps if a svg is uploaded editable fields for width and height should appear with default values corresponding to the uploaded file

**Comment by pjotrsavitski** [comment]
It does behave quite well as an image. Allowing upload only took a few modifications (this is still unfinished as determining the size is a bit tricky). The editor that allows image resize and rotation also works well enough with it. The only side effect is that the resulting image becomes a .png file instead. I am doing these modifications anyway. If those are accepted into the core, then it would be even better. I still have a few things to try out, mainly add the code for meaningful width and height determination and check that it works well in all situations. I will try to fork the repo, port the changes from my current private one and make a pull request.

It could possibly have a few issues with active content being present, but that should not be an issue if those are used with  elements and stay well away from <embed>, <object> or <iframe>.

**Comment by timothyylim** [comment]
Great. I'll see that your pull request is reviewed.

**Comment by pjotrsavitski** [comment]
Added the pull request. The size determination logic could be made better. But that should be a good enough starting point.

**Comment by falcon-git** [comment]
Thanks! Issue was added. Link is in the PR. If you want to improve the image handling before it is reviewed you probably have a couple of weeks to do it at least.

**Comment by cperg** [comment]
This may superfluous but here are my 2 cents.
::any svg has an original ratio but not a specific size. setting one or the other (either height or width) with an actual value of px em or vw should work, as well as a percent of the holding container.

**Comment by pjotrsavitski** [comment]
Well, an svg might have no size hint at all (probably not in case of ones exported from image editors). These sizes might even work the way there were, but the other image types seem to be having numeric values. Those could later on be used by the H5P types to build the visuals. The **Presentation** ones seems to be allowing to set the size of included images. Images are sized according to ratio, I would guess that it is being calculated based on the values of **width** and **height** being stored.

The main aim was to get svg usable within an image field, meaning that it would act as one as much as possible. If the svg being uploaded is malformed (missing the required values), then it does not count as an image in that context.

There is no database column for these values and it is hard to determine what suits and what not, yet it would be safest to assume the numeric ones are a requirement.

**Comment by fnoks** [comment]
@cperg : Your merge a few days ago makes no sense to me - was it by accident?

**Comment by icc** [comment]
I see two issues merging this:

1. We are losing width, height, mime which are quite important to many editor widgets.
2. This will not work with the current image editor?

**Comment by pjotrsavitski** [comment]
@icc There is a bit newer pull request for the same issue found [here](https://github.com/h5p/h5p-editor-php-library/pull/38) though it now seems to be in conflict with the codebase that has moved on.

It should keep the the width and height, though there could be issues with values as those did not seem to always be in pixels (if I remember that correctly).

As for image editor (again, not 100% sure because of the time gap), but the SVG will be converted to PNG if one tries to edit it in any way. At least that is how it behaved back then.

**Comment by icc** [comment]
Thank you. We'll go with #38 then since it includes the same as in this one + the fixes.

**Pull request closed without merging**
