### PR TITLE
Aspect ratio for videos

### PR DESCRIPTION
**Pull request by tsivert**
Send aspect ratio for the video(given it's in the providers list) in order to let h5p-editor-course-presentation adjust the size of the "video container" when inserted into a Course Presentation.

### CODE REVIEW

**Comment by tsivert** [comment]
Part of the pull request [Resize video container](https://github.com/h5p/h5p-editor-course-presentation/pull/20)

**Comment by icc** [comment]
Now that we have the default `16:9` in CPEditor, will we be needing this since it's always the same? 

(Also, I believe YT videos can be 4:3 (+25px to height for controls) as well.)

**Comment by tsivert** [comment]
Yes and no. `16:9` happens to be the aspect ratio for the video streaming service I'm integrating with in my project. But others might have different aspect ratios. This enables the possibility to set your own aspect ratio if you add other providers to the list without too much effort.

**Comment by icc** [comment]
Ah, of course, I was mixing up some editor/view stuff

**Pull request merged**
